"""
Auto-generated State class with SQLAlchemy methods.

This class is generated by splurge-sql-generator.
Do not edit this file manually - it will be overwritten.
"""

import logging
from typing import List
from sqlalchemy import text
from sqlalchemy.engine import Connection, Result
from sqlalchemy.engine.row import Row


class State:
    """
    State with SQLAlchemy-based database operations.

    This class provides only class methods (for explicit connection and transaction control).

    Attributes:
        logger: Class-level logger used by default for all operations.
    """

    logger = logging.getLogger(f"{__name__}.State")
    # Attach a NullHandler to avoid 'No handler' warnings in CLI/standalone usage
    if not logger.handlers:
        logger.addHandler(logging.NullHandler())

    @classmethod
    def create_table(
        cls,
        *,
        connection: Connection,
    ) -> Result:
        """
        Other operation: create_table (class method).
        Statement type: execute
        Args:
            connection: SQLAlchemy database connection

        Returns:
            SQLAlchemy Result object
        """
        logger = cls.logger

        logger.debug("Executing create_table operation")

        sql = """
        CREATE TABLE IF NOT EXISTS state (
            id VARCHAR(36) PRIMARY KEY NOT NULL,
            name VARCHAR(128) NOT NULL,
            alias VARCHAR(128) NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            UNIQUE KEY (alias)
        )
        """

        # Execute SQL query
        try:
            result = connection.execute(text(sql))

            # Execute non-select operation
            logger.debug("Executed non-select operation")
            return result
        except Exception as e:
            logger.error("Error in create_table operation: %s", str(e))
            raise

    @classmethod
    def insert_state(
        cls,
        *,
        connection: Connection,
        id: str,
        name: str,
        alias: str,
    ) -> Result:
        """
        Insert operation: insert_state (class method).
        Statement type: execute
        Args:
            connection: SQLAlchemy database connection
            id: Parameter for id
            name: Parameter for name
            alias: Parameter for alias

        Returns:
            SQLAlchemy Result object
        """
        logger = cls.logger

        logger.debug("Executing insert_state operation")

        sql = """
        INSERT INTO state (id, name, alias, created_at, updated_at) 
        VALUES (
            :id,
            :name,
            :alias,
            NOW(),
            NOW()
        )
        """

        # Prepare parameters
        params = {
            "id": id,
            "name": name,
            "alias": alias,
        }
        logger.debug("Parameters: %s", params)

        # Execute SQL query
        try:
            result = connection.execute(text(sql), params)

            # Execute non-select operation
            logger.debug("Executed non-select operation")
            return result
        except Exception as e:
            logger.error("Error in insert_state operation: %s", str(e))
            raise

    @classmethod
    def update_state(
        cls,
        *,
        connection: Connection,
        name: str,
        alias: str,
        id: str,
    ) -> Result:
        """
        Update operation: update_state (class method).
        Statement type: execute
        Args:
            connection: SQLAlchemy database connection
            name: Parameter for name
            alias: Parameter for alias
            id: Parameter for id

        Returns:
            SQLAlchemy Result object
        """
        logger = cls.logger

        logger.debug("Executing update_state operation")

        sql = """
        UPDATE state 
        SET 
            name = :name, 
            alias = :alias, 
            updated_at = NOW() 
        WHERE id = :id
        """

        # Prepare parameters
        params = {
            "name": name,
            "alias": alias,
            "id": id,
        }
        logger.debug("Parameters: %s", params)

        # Execute SQL query
        try:
            result = connection.execute(text(sql), params)

            # Execute non-select operation
            logger.debug("Executed non-select operation")
            return result
        except Exception as e:
            logger.error("Error in update_state operation: %s", str(e))
            raise

    @classmethod
    def get_state_by_id(
        cls,
        *,
        connection: Connection,
        id: str,
    ) -> List[Row]:
        """
        Select operation: get_state_by_id (class method).
        Statement type: fetch
        Args:
            connection: SQLAlchemy database connection
            id: Parameter for id

        Returns:
            List of result rows
        """
        logger = cls.logger

        logger.debug("Executing get_state_by_id operation")

        sql = """
        SELECT * 
        FROM state 
        WHERE id = :id
        """

        # Prepare parameters
        params = {
            "id": id,
        }
        logger.debug("Parameters: %s", params)

        # Execute SQL query
        try:
            result = connection.execute(text(sql), params)

            # Fetch results
            rows = result.fetchall()
            logger.debug("Fetched %d rows", len(rows))
            return rows
        except Exception as e:
            logger.error("Error in get_state_by_id operation: %s", str(e))
            raise

    @classmethod
    def get_state_by_alias(
        cls,
        *,
        connection: Connection,
        alias: str,
    ) -> List[Row]:
        """
        Select operation: get_state_by_alias (class method).
        Statement type: fetch
        Args:
            connection: SQLAlchemy database connection
            alias: Parameter for alias

        Returns:
            List of result rows
        """
        logger = cls.logger

        logger.debug("Executing get_state_by_alias operation")

        sql = """
        SELECT * 
        FROM state 
        WHERE alias = :alias
        """

        # Prepare parameters
        params = {
            "alias": alias,
        }
        logger.debug("Parameters: %s", params)

        # Execute SQL query
        try:
            result = connection.execute(text(sql), params)

            # Fetch results
            rows = result.fetchall()
            logger.debug("Fetched %d rows", len(rows))
            return rows
        except Exception as e:
            logger.error("Error in get_state_by_alias operation: %s", str(e))
            raise

    @classmethod
    def get_all_states(
        cls,
        *,
        connection: Connection,
    ) -> List[Row]:
        """
        Select operation: get_all_states (class method).
        Statement type: fetch
        Args:
            connection: SQLAlchemy database connection

        Returns:
            List of result rows
        """
        logger = cls.logger

        logger.debug("Executing get_all_states operation")

        sql = """
        SELECT * 
        FROM state
        ORDER BY name
        """

        # Execute SQL query
        try:
            result = connection.execute(text(sql))

            # Fetch results
            rows = result.fetchall()
            logger.debug("Fetched %d rows", len(rows))
            return rows
        except Exception as e:
            logger.error("Error in get_all_states operation: %s", str(e))
            raise
